# Generated by Django 3.0.1 on 2020-06-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200606_1429'),
    ]

    operations = [
    ]
