# Generated by Django 3.0.1 on 2020-06-13 17:38


from django.db import migrations
from django.conf import settings

def make_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('accounts', 'Profile')
    profiles = [Profile(user=user) for user in User.objects.filter(profile=None)]
    Profile.objects.bulk_create(profiles)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200606_1830'),
    ]

    operations = [
        migrations.RunPython(make_profiles),
    ]
