# Generated by Django 3.0.1 on 2020-06-14 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200614_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='useful_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 19, 32, 34, 566557)),
        ),
    ]
