# Generated by Django 3.0.1 on 2020-06-14 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200614_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='useful_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 19, 36, 1, 270555)),
        ),
    ]
