# Generated by Django 3.0.1 on 2020-07-14 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200629_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 13, 7, 39, 684003)),
        ),
    ]
