# Generated by Django 3.0.1 on 2020-06-17 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_auto_20200617_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 6, 17, 13, 18, 26, 602964))),
                ('tags', models.CharField(blank=True, max_length=30)),
                ('public', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='postimg/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
