# Generated by Django 3.0.1 on 2020-07-14 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200714_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 13, 9, 8, 647254)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 13, 9, 8, 646257)),
        ),
    ]
